# Generated by Django 4.1.6 on 2023-02-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('lat', models.CharField(max_length=53)),
                ('lng', models.CharField(max_length=53)),
                ('period', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('price', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
