# Generated by Django 4.1.6 on 2023-02-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampsiteJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
