# Generated by Django 4.1.6 on 2023-02-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campsite', '0002_campsitejson'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CampsiteJson',
            new_name='JsonFile',
        ),
    ]
