# Generated by Django 4.1.6 on 2023-02-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campsite', '0003_rename_campsitejson_jsonfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvenienceStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('lat', models.CharField(max_length=53)),
                ('lng', models.CharField(max_length=53)),
                ('phone', models.CharField(max_length=15)),
                ('description', models.CharField(default='unknown', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Spa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('lat', models.CharField(max_length=53)),
                ('lng', models.CharField(max_length=53)),
                ('hours', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('price', models.CharField(max_length=300)),
                ('description', models.CharField(default='unknown', max_length=500)),
            ],
        ),
    ]
