# Generated by Django 4.1.6 on 2023-02-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campsite', '0004_conveniencestore_spa'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonfile',
            name='name',
            field=models.CharField(default='jsonfile', max_length=20),
        ),
    ]
