# Generated by Django 4.1.6 on 2023-02-23 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campsite', '0005_jsonfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonfile',
            name='name',
        ),
        migrations.CreateModel(
            name='SpaJsonFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campsite.jsonfile')),
            ],
        ),
        migrations.CreateModel(
            name='ConvenienceStoreJsonFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campsite.jsonfile')),
            ],
        ),
        migrations.CreateModel(
            name='CampsiteJsonFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campsite.jsonfile')),
            ],
        ),
    ]
