# Generated by Django 4.1.6 on 2023-02-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campsite', '0006_remove_jsonfile_name_spajsonfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campsitejsonfile',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='conveniencestorejsonfile',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='spajsonfile',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
