# Generated by Django 4.1.6 on 2023-02-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campsite', '0007_alter_campsitejsonfile_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campsitejsonfile',
            old_name='file',
            new_name='campsite',
        ),
        migrations.RenameField(
            model_name='conveniencestorejsonfile',
            old_name='file',
            new_name='convenience',
        ),
        migrations.RenameField(
            model_name='spajsonfile',
            old_name='file',
            new_name='spa',
        ),
    ]
