# Generated by Django 4.1.6 on 2023-02-23 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campsite', '0008_rename_file_campsitejsonfile_campsite_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JsonFile',
        ),
    ]
