# Generated by Django 4.1.6 on 2023-02-24 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campsite', '0009_delete_jsonfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spa',
            old_name='hours',
            new_name='period',
        ),
    ]
