# Generated by Django 4.1.6 on 2023-02-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campsite', '0010_rename_hours_spa_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsite',
            name='iconpath',
            field=models.CharField(default='iconpath', max_length=30),
        ),
        migrations.AddField(
            model_name='conveniencestore',
            name='iconpath',
            field=models.CharField(default='iconpath', max_length=30),
        ),
        migrations.AddField(
            model_name='spa',
            name='iconpath',
            field=models.CharField(default='iconpath', max_length=30),
        ),
    ]
