# Generated by Django 4.1.6 on 2023-03-21 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campsite', '0012_spacomment_conveniencestorecomment_campsitecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starRate', models.IntegerField()),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('lat', models.CharField(max_length=53)),
                ('lng', models.CharField(max_length=53)),
                ('period', models.CharField(default='-', max_length=30)),
                ('phone', models.CharField(default='-', max_length=15)),
                ('price', models.CharField(default='-', max_length=300)),
                ('description', models.CharField(default='-', max_length=500)),
                ('iconpath', models.CharField(default='iconpath', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='campsitecomment',
            name='spot',
        ),
        migrations.RemoveField(
            model_name='campsitecomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='conveniencestorecomment',
            name='spot',
        ),
        migrations.RemoveField(
            model_name='conveniencestorecomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='spacomment',
            name='spot',
        ),
        migrations.RemoveField(
            model_name='spacomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Campsite',
        ),
        migrations.DeleteModel(
            name='CampsiteComment',
        ),
        migrations.DeleteModel(
            name='ConvenienceStore',
        ),
        migrations.DeleteModel(
            name='ConvenienceStoreComment',
        ),
        migrations.DeleteModel(
            name='Spa',
        ),
        migrations.DeleteModel(
            name='SpaComment',
        ),
        migrations.AddField(
            model_name='comment',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='campsite.spot'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
