# Generated by Django 4.1.6 on 2023-03-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campsite', '0013_comment_spot_remove_campsitecomment_spot_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampsiteJsonFile',
        ),
        migrations.DeleteModel(
            name='ConvenienceStoreJsonFile',
        ),
        migrations.DeleteModel(
            name='SpaJsonFile',
        ),
    ]
