# Generated by Django 4.1.6 on 2023-03-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campsite', '0014_delete_campsitejsonfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='key',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
