# Generated by Django 4.1.6 on 2023-03-21 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campsite', '0015_comment_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotImageUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='campsite.spot')),
            ],
        ),
    ]
