# Generated by Django 4.1.6 on 2023-03-22 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campsite', '0016_spotimageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_comment', to='campsite.spot'),
        ),
        migrations.AlterField(
            model_name='spotimageurl',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_image_url', to='campsite.spot'),
        ),
    ]
