name: CI
on:
  push:
    branches: [hoge]
  pull_request:
    branches: [hoge]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true # Git LFS を有効にする

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      - name: Setup .env file
        working-directory: ./docker/back/django_project
        run: echo "${{ secrets.LOCAL_ENV_FILE }}" > .local.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build backend image
        uses: docker/build-push-action@v4
        with:
          push: false
          builder: ${{ steps.buildx.outputs.name }}
          tags: my-backend-image:latest
          load: true
          context: ./docker/back
          file: ./docker/back/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Save cache
        if: always()
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-new
          key: ${{ runner.os }}-buildx-${{ github.sha }}

      - name: Build and start the services
        run: |
          docker compose -f docker-compose.ci.yml up -d --build
          echo "Waiting for Django server to be ready..."
          while true; do
            if docker compose logs back 2>&1 | grep -q "Quit the server with CONTROL-C."; then
              echo "Django server is ready."
              break
            fi
            sleep 1
          done

      - name: Run Django tests
        run: |
          docker compose -f docker-compose.ci.yml run back python manage.py migrate
          docker compose -f docker-compose.ci.yml exec back python manage.py test -r

      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose.ci.yml down
