
name: Docker Setup

on:
  workflow_call:
    secrets:
      LOCAL_ENV_FILE:
        required: true


jobs:
  build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     - name: Setup .env file
       working-directory: ./docker/back/django_project
       run: echo "${{ secrets.LOCAL_ENV_FILE }}" > .local.env
       
     - name: Build and start the services
       run: |
         docker compose build
         docker compose up -d
         
         echo "Waiting for Django server to be ready..."
         while true; do
           if docker compose logs back 2>&1 | grep -q "Quit the server with CONTROL-C."; then
             echo "Django server is ready."
             break
           fi
           sleep 1
         done
