
name: Docker Setup

on:
  workflow_call:
    secrets:
      LOCAL_ENV_FILE:
        required: true
  workflow_dispatch:


env:
  AWS_REGION: ap-northeast-1
  ECR_REPOSITORY_NGINX: campfinder_nginx
  ECR_REPOSITORY_BACK: campfinder_back
  ECR_REGISTRY: public.ecr.aws/x4o0n4b7

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     - name: Setup .env file
       working-directory: ./docker/back/django_project
       run: echo "${{ secrets.LOCAL_ENV_FILE }}" > .local.env
       
     - name: Build and start the services
       run: |
         docker compose build
         docker compose up -d
         
         echo "Waiting for Django server to be ready..."
         while true; do
           if docker compose logs back 2>&1 | grep -q "Quit the server with CONTROL-C."; then
             echo "Django server is ready."
             break
           fi
           sleep 1
         done
         
     - name: Configure AWS credentials
       run: |
         aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws configure set default.region ${{ env.AWS_REGION }}
         
     - name: Login to Amazon ECR
       id: login-ecr
       run: |
         aws ecr-public get-login-password --region $AWS_REGION |
         docker login --username AWS --password-stdin $ECR_REGISTRY
         
     - name: Push images to Amazon ECR
       run: |
         docker tag campfinder-db:latest $ECR_REGISTRY/$ECR_REPOSITORY_DB:latest
         docker tag campfinder-back:latest $ECR_REGISTRY/$ECR_REPOSITORY_BACK:latest
         docker tag campfinder-nginx:latest $ECR_REGISTRY/$ECR_REPOSITORY_NGINX:latest

         docker push $ECR_REGISTRY/$ECR_REPOSITORY_DB:latest
         docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACK:latest
         docker push $ECR_REGISTRY/$ECR_REPOSITORY_NGINX:latest
         

      
