name: Django CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     - name: Build and start the services
       run: |
         docker compose build
         docker compose up -d
         sleep 15s
         docker ps -a
     - name: Run Django tests
       run: |
         docker compose exec back python manage.py test -r
