name: Django CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker
        uses: ./.github/workflows/docker-setup.yml@main
      - name: Run Django test
        run: |
          docker compose exec back python manage.py test -r
      - name: Cleanup
        if: always()
        run: docker compose down -v
