name: Django CI
on:
  push:
    #branches: [ main ]
    branches: [ hoge ]
  pull_request:
    #branches: [ main ]
    branches: [ hoge ]
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/docker-setup.yml
    secrets:
      LOCAL_ENV_FILE: ${{ secrets.LOCAL_ENV_FILE }}
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Django test
        run: |
          docker compose exec back python manage.py test -r
      - name: Cleanup
        if: always()
        run: docker compose down -v
